
- HK2UN_IP
- HK2TGF_IP
- INPUT-HK2UN
- INPUT-HK2TGF


cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o tr_HK2UN-IP_1.fastq.gz -p tr_HK2UN-IP_2.fastq.gz HK2UN-IP_1.fastq.gz HK2UN-IP_2.fastq.gz ;
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o tr_HK2TGF-IP_1.fastq.gz -p tr_HK2TGF-IP_2.fastq.gz HK2TGF-IP_1.fastq.gz HK2TGF-IP_2.fastq.gz ;
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o tr_INPUT-HK2TGF_1.fastq.gz -p tr_INPUT-HK2TGF_2.fastq.gz INPUT-HK2TGF_1.fastq.gz INPUT-HK2TGF_2.fastq.gz ;
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o tr_INPUT-HK2UN_1.fastq.gz -p tr_INPUT-HK2UN_2.fastq.gz INPUT-HK2UN_1.fastq.gz INPUT-HK2UN_2.fastq.gz